### ISSUE TITLE
TO-DO for new API

### ISSUE THREAD

**Issue by larryTheCoder** [larryTheCoder/SkyWarsForPE#7]
### TO-DO list for me
- [x]  Add shop for SkyWars
- [ ]  Prevent players for doing fake fly (stuck in air)
- [ ]  Add new language `Spanish, Chinese and more`
- [x]  Fix all bugs and crashes when adding this plugin
